---
title: "Next Word Prediction Widget"
author: "Abid Al Reza"
date: "11/13/2020"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### Overview

This presentation was generated as a requirement for completion of the coursera course titled "Developing Data Products."

The application (Auto Loan Calculator) was developed using Shiny and can be observed [here](https://abidgen.shinyapps.io/auto_loan_calculator/).

Source codes for the presentation (Rmd file) and application (ui.R and server.R) are hosted at [Github](https://github.com/abidgen/Car_loan_calculator).



## Shiny Application: Auto Loan Calculator

This application calculates monthly payment amount based on the following variable,

- Auto Price
- Loan Term
- Yearly Interest rate
- Down Payment
- Trade-in Value
- sales Tax Rate
- Title, Registration and Other Fees

This application also has the option to include all fees in the loan. 



## Instructions

- This app accepts positive numeric values for input variables in the left sidebar panel. 
- User needs to input values in the respective boxes and hit "submit" button to initiate calculation. The results are displayed in the main panel. 
- User needs to enter values for all variables. Keeping them empty will generate error. 
- If the user wants to do calculations with all fees (including sales tax) in the loan, they have to check the "Include all fees in the loan" box.



## Application Layout and sample code
